---
#バージョン指定はV2からは無視されるため記載不要
services:
  # 2. MySQL データベースサービス
  db:
    expose:
      - "3306" # バックエンドとの疎通のため内部のみで開放(portsは厳禁)
    restart: always

  app:
    expose:
      - "8080"
    restart: always

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile # Dockerfileにnginxで立つようになってるのでimage不要
    ports:
      - "80:80" # フロントはnginxが立つのでポートはHTTPを許可する
    restart: always
    depends_on:
      - app

volumes:
  mysql-data: # 名前付きボリュームの定義
